### model
# NOTE: when in stage 1 training, change 'model_name_or_path' to the local path of pre-trained ckpt of Qwen2-VL
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
# deepspeed: /mnt/data2/wgk/SurgVidLM-main/LLaMA-Factory/examples/deepspeed/ds_z2_config.json

### dataset
dataset: svu-31k-full-video
template: qwen2_vl
cutoff_len: 25000
max_samples: 2500 # for stage 1 training, set max_samples to 2500
overwrite_cache: true
preprocessing_num_workers: 16 # increase the number of workers to accelerate the preprocessing process
preprocessing_batch_size: 128
dataloader_num_workers: 1


### output
tokenized_path: /mnt/data2/wgk/surgvidlm_project/surgvidlm_open/LLaMA-Factory/saves/tokenizer/tokenizer_full_video #check
output_dir: /mnt/data2/wgk/surgvidlm_project/surgvidlm_open/LLaMA-Factory/saves/lora/qwen2_vl_full_video #check
logging_steps: 1
save_strategy: "steps"
save_steps: 37
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

